apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: f8iqdefza-nodejs 
  janus-idp.io/tekton: f8iqdefza-nodejs
  backstage.io/kubernetes-id: f8iqdefza-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: f8iqdefza-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml