apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: f8iqdefza-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:b1ef7f6d45b3b9cbbe01411d4146dbea7f0fa062@sha256:e763ffa12b0ef9d91ef52bb538e97299725748571a6d46000a46880bb0d39ae5
          name: container-image
